name: Test API Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup gradle
      run: chmod +x gradlew
      
    - name: Execute Test
      run: ./gradlew test

      #archieve test result
    - name: Archive TestNG Reports
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: TestNG-Execution-Report
        path: build/reports/tests/test/
